name: Generate GitHub Snake

on:
  schedule:
    # Запускать каждые 12 часов (можно изменить, например, "0 */6 * * *" для каждых 6 часов)
    - cron: "0 */12 * * *"
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions
  push:
    branches:
      - main # Убедитесь, что это ваша основная ветка (может быть 'master')

jobs:
  generate:
    runs-on: ubuntu-latest
    # Эти права КРИТИЧЕСКИ важны, чтобы Action мог коммитить файлы обратно в репозиторий
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }} # Автоматически подставит ваш ник (wastedswl)
          # Список выходных файлов. Убедитесь, что путь здесь соответствует тому, что вы ожидаете.
          # Я рекомендую использовать папку 'dist' для сгенерированных файлов.
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58a6ff&color_dots=#bfd7ff,#82b1ff,#6495ed,#4682b4,#00509d
            dist/ocean.svg?color_snake=orange&color_dots=#bfd7ff,#82b1ff,#6495ed,#4682b4,#00509d
        # Action Platane/snk@v3 должен сам коммитить изменения.
        # Если этого не происходит, раскомментируйте следующий шаг:
      # - name: Commit and push changes
      #   if: ${{ success() }} # Запускать только если предыдущий шаг успешен
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: github-actions[bot]
      #     author_email: 41898282+github-actions[bot]@users.noreply.github.com
      #     message: "docs: generate contribution snake 🐍"
      #     add: 'dist/*.svg' # Добавляем все сгенерированные SVG из папки dist
      #     push: true
